### ISSUE TITLE
how can i use this?

### ISSUE THREAD

**Issue by Kiritomo** [umgi/hibiki-dl#1]

**Comment by emicharm** [comment]
A simple usage guide is now written in readme

**Comment by Kiritomo** [comment]
run error in debain10, error message:
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.normalize (path.js:1005:5)
    at /root/podcast-dl/lib/history.js:5:25
    at Object.<anonymous> (/root/podcast-dl/lib/history.js:23:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by emicharm** [comment]
It should work now.

**Comment by Kiritomo** [comment]
ok, it work now, thank you.
